#pragma once

#include "Types.h"
#include "CoreMacro.h"
#include "CoreTLS.h"
#include "CoreGlobal.h"

#include <windows.h>
#include <iostream>
#include <functional>
#include <string>
#include <string_view>
#include <tchar.h>
#include <ranges>
#include <algorithm>
#include <shared_mutex>
#include <optional>
#include <concepts>
#include <coroutine>
#include <cassert>
#include <thread>
#include <chrono>
#include <future>
#include <vector>
#include <array>
#include <list>
#include <queue>
#include <stack>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <DbgHelp.h>
#include <winsock2.h>
#include <mswsock.h>
#include <ws2tcpip.h>
#include <concurrent_priority_queue.h>
#include "concurrentqueue.h"
#pragma comment(lib, "ws2_32.lib")

#include "IDGenerator.hpp"
#include "Lock.h"
#include "ObjectPool.hpp"
#include "TypeCast.h"
#include "MemoryMgr.h"
#include "MemoryHeader.hpp"
#include "func.h"
#include "Singleton.hpp"
#include "SpinLock.hpp"
#include "SRWLock.hpp"
#include "MPSCQueue.hpp"
#include "ConcurrentHash.hpp"
#include "PacketHeader.h"
#include "TaskQueueable.h"
#include "SendBufferMgr.h"
#include "SendBuffer.h"
#include "CoRoutine.hpp"
#include "Logger.h"
#include "ThreadMgr.h"
#include "LinkedHashMap.hpp"
#include "Interpolator.hpp"
#include "ID_Ptr.hpp"
